refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
root:
  level: trace
  appenders:
    - stdout
loggers:
  mio:
    level: warn
  hyper:
    level: warn
  want:
    level: warn
  zhelezyaka::sqlite:
    level: warn
